# Generated by Django 5.0.6 on 2024-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('EARNING', 'User got earnings'), ('DIVIDEND', 'User receive dividend on investment'), ('LOAN-GRANTED', 'Loan request for user granted'), ('USER-TARGET', 'Notification for user on their savings target')], default='EARNING')),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
