# Generated by Django 5.0.6 on 2024-07-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('EARNING', 'User got earnings'), ('DIVIDEND', 'User receive dividend on investment'), ('LOAN-UPDATE', 'Update on loan request'), ('USER-TARGET', 'Notification for user on their savings target')], default='EARNING'),
        ),
    ]
