# Generated by Django 5.0.6 on 2024-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('EARNING', 'User got earnings'), ('DIVIDEND', 'User receive dividend on investment'), ('LOAN-UPDATE', 'Update on loan request'), ('USER-TARGET', 'Notification for user on their savings target'), ('OTHERS', 'Other form of notification')], default='EARNING'),
        ),
    ]
