# Generated by Django 5.0.6 on 2024-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('WALLET-CREDIT', 'Wallet Credit'), ('Withdrawal', 'Withdrawal'), ('DATA_PURCHASE', 'Data purchase')], default='WALLET-CREDIT', max_length=250),
        ),
    ]
