# Generated by Django 5.0.6 on 2024-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='revenue',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
