# Generated by Django 5.0.6 on 2024-08-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(default='Bank Transfer/Akinola Samson', max_length=1000),
            preserve_default=False,
        ),
    ]
