# Generated by Django 5.0.6 on 2024-08-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_message_transaction_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
