# Generated by Django 5.0.6 on 2024-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_investmentplan_activities_userinvestments'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
