# Generated by Django 5.0.6 on 2024-05-26 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('goal_met', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily contribution'), ('Weekly', 'Weekly contribution'), ('Monthly', 'Monthly contribution')], default='Daily')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
