# Generated by Django 5.0.6 on 2024-05-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usersavings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavings',
            name='saved',
            field=models.BigIntegerField(default=0),
        ),
    ]
