# Generated by Django 5.0.6 on 2024-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usersavings_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavings',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily contribution'), ('WEEKLY', 'Weekly contribution'), ('MONTHLY', 'Monthly contribution')], default='DAILY'),
        ),
    ]
