# Generated by Django 5.0.6 on 2024-05-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeHavenAPIDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_token', models.TextField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('ibs_client_id', models.CharField(max_length=255)),
                ('ibs_user_id', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
