# Generated by Django 5.0.6 on 2024-05-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_safehavenapidetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn_verify_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_verify_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
