# Generated by Django 5.0.6 on 2024-06-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_bvn_verify_details_user_nin_verify_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
