# Generated by Django 5.0.6 on 2024-06-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_coporativemembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coporativemembership',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coporativemembership',
            name='membership_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
