# Generated by Django 5.0.6 on 2024-06-03 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_coporativemembership_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor1_agreed', models.BooleanField(default=False)),
                ('guarantor2_agreed', models.BooleanField(default=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('amount_repayed', models.PositiveBigIntegerField(default=0)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('duration_in_months', models.PositiveIntegerField(default=6)),
                ('interest_rate', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('PENDING', 'Loan waiting for admin approval'), ('APPROVED', 'Loan approved by admin'), ('REJECTED', 'Loan Rejected by admin'), ('REPAYED', 'Loan fully repayed'), ('OVER-DUE', 'Loan overdued')], default='PENDING', max_length=10)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('guarantor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranter_1', to=settings.AUTH_USER_MODEL)),
                ('guarantor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranter_2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
