# Generated by Django 5.0.6 on 2024-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('DEBIT', 'User got debited'), ('CREDIT', 'User got credited')], default='DEBIT', max_length=255),
        ),
    ]
