# Generated by Django 5.0.6 on 2024-06-06 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_activities_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='referal_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
