# Generated by Django 5.0.6 on 2024-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_total_referal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavings',
            name='title',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('CAR-PURCHASE', 'Car purchase'), ('VACATION', 'Vacations'), ('GARGET-PURCHASE', 'Garget purchase'), ('MISCELLANEOUS', 'Miscellaneous')], default='BIRTHDAY', max_length=35),
        ),
    ]
