# Generated by Django 5.0.6 on 2024-07-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_usersavings_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinvestments',
            unique_together={('user', 'investment')},
        ),
    ]
