# Generated by Django 5.0.6 on 2024-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_userinvestments_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='investors',
            field=models.IntegerField(default=0),
        ),
    ]
