# Generated by Django 5.0.6 on 2024-07-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_userinvestments_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersavings',
            old_name='title',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='usersavings',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='usersavings',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usersavings',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersavings',
            name='withdrawal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersavings',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
