# Generated by Django 5.0.6 on 2024-07-27 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_savingsactivities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsactivities',
            name='activity_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('DIVIDENDS', 'Dividends')], default='DEPOSIT', max_length=255),
        ),
        migrations.CreateModel(
            name='CoporativeActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('activity_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('DIVIDENDS', 'Dividends')], default='DEPOSIT', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dividend_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
