# Generated by Django 5.0.6 on 2024-07-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_savingsactivities_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coporativeactivities',
            name='user',
        ),
        migrations.AddField(
            model_name='coporativeactivities',
            name='user_coop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_coop_activity', to='user.coporativemembership'),
            preserve_default=False,
        ),
    ]
