# Generated by Django 5.0.6 on 2024-07-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_remove_coporativeactivities_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavings',
            name='type',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('CAR-PURCHASE', 'Car purchase'), ('VACATION', 'Vacations'), ('GADGET-PURCHASE', 'Gadget purchase'), ('MISCELLANEOUS', 'Miscellaneous')], default='BIRTHDAY', max_length=35),
        ),
    ]
