# Generated by Django 5.0.6 on 2024-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_withdrawal_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coporativeactivities',
            name='balance',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
