# Generated by Django 5.0.6 on 2024-08-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_usersavings_cycle_alter_userinvestments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavings',
            name='cycle',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
