# Generated by Django 5.0.6 on 2024-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_usersavings_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavings',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
