# Generated by Django 5.0.6 on 2024-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_usersavings_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavings',
            name='balance',
        ),
        migrations.AddField(
            model_name='savingsactivities',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
