# Generated by Django 5.0.6 on 2024-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_loan_repayment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavings',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
