# Generated by Django 5.0.6 on 2024-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_usersavings_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavings',
            name='all_time_saved',
            field=models.BigIntegerField(default=0),
        ),
    ]
