# Generated by Django 5.0.6 on 2024-08-20 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_usersavings_all_time_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_fee', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinvestments')),
            ],
        ),
    ]
