# Generated by Django 5.0.6 on 2024-08-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_cancelinvestment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CancelInvestment',
            new_name='InvestmentCancel',
        ),
    ]
