# Generated by Django 5.0.6 on 2024-08-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_rename_cancelinvestment_investmentcancel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentcancel',
            old_name='penalty_fee',
            new_name='penalty',
        ),
    ]
