# Generated by Django 5.0.6 on 2024-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_usersavings_day_month_usersavings_day_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsactivities',
            name='interest',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersavings',
            name='interest',
            field=models.BigIntegerField(default=0),
        ),
    ]
