# Generated by Django 5.0.6 on 2024-08-24 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_rename_created_date_transaction_created_at'),
        ('user', '0048_alter_userinvestments_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_withdrawal_transaction', to='transaction.transaction'),
        ),
    ]
