# Generated by Django 5.0.6 on 2024-09-14 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_withdrawal_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpasswordtoken',
            name='token',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
