# Generated by Django 5.0.6 on 2024-09-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_investmentplan_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='duration',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
