# Generated by Django 5.0.6 on 2024-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_investmentplan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coporativemembership',
            name='dividend',
            field=models.IntegerField(default=0),
        ),
    ]
