# Generated by Django 5.0.6 on 2024-09-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_coporativemembership_dividend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsactivities',
            old_name='interest',
            new_name='all_time_interest',
        ),
    ]
