# Generated by Django 5.0.6 on 2024-09-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_rename_interest_savingsactivities_all_time_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsactivities',
            old_name='all_time_interest',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='usersavings',
            old_name='interest',
            new_name='all_time_interest',
        ),
    ]
