# Generated by Django 5.0.6 on 2024-09-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_rename_all_time_interest_savingsactivities_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavings',
            name='interest',
            field=models.BigIntegerField(default=0),
        ),
    ]
