# Generated by Django 5.0.6 on 2024-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_usersavings_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='guarantor1_agreed',
            field=models.CharField(choices=[('PENDING', 'Waiting for guarantor approval'), ('APPROVED', 'Rejected by guarantor'), ('REJECTED', 'Accepted by Guarantor')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor2_agreed',
            field=models.CharField(choices=[('PENDING', 'Waiting for guarantor approval'), ('APPROVED', 'Rejected by guarantor'), ('REJECTED', 'Accepted by Guarantor')], default='PENDING', max_length=10),
        ),
    ]
