# Generated by Django 5.0.6 on 2024-09-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_alter_loan_guarantor1_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestments',
            name='interest',
            field=models.IntegerField(default=0),
        ),
    ]
