# Generated by Django 5.0.6 on 2024-09-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_usersavings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coporativemembership',
            name='monthly_dividend',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
