# Generated by Django 5.0.6 on 2024-10-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_coporativemembership_monthly_dividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAndAirtimeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrence_code', models.CharField(editable=False, max_length=50)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('network', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('package', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('DATA', 'Data purchase'), ('AIRTIME', 'Airtime purchase')], default='DATA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
