# Generated by Django 5.0.6 on 2024-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_dataandairtimeactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavings',
            name='type',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('CHILDREN', 'Children'), ('VACATION', 'Vacations'), ('RETIREMENT', 'Retirement'), ('MISCELLANEOUS', 'Miscellaneous')], default='BIRTHDAY', max_length=35),
        ),
    ]
